server:
  port: 8868

feign:
  httpclient:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: myspringcloud-upload
    prefer-ip-address: true

spring:
  application:
    name: myspringcloud-upload
  redis:
      host: 127.0.0.1
      port: 6379
      password:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
      timeout: 30000
  http:
    multipart:
      max-file-size: 200Mb # Max file size，默认1M
      max-request-size: 2500Mb     # Max request size，默认10M
