server:
  port: 9527

spring:
  application:
    name: myspringcloud-zuul-gateway
  redis:
      host: 127.0.0.1
      port: 6379
      password:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
      timeout: 30000
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


info:
  app.name: scauly-myspringcloud
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

zuul:
  prefix: /scauly
  ignored-services: "*"
  routes:
    role.serviceId: myspringcloud-role9001
    role.path: /role/**
    fund.serviceId: myspringcloud-fund9002
    fund.path: /fund/**
    ow.serviceId: myspringcloud-ow9003
    ow.path: /ow/**