server:
  port: 9003

feign:
  httpclient:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: myspringcloud-ow9003-Consumer-hystrix
    prefer-ip-address: true

spring:
  application:
    name: myspringcloud-ow9003

