server:
  port: 9527

spring:
  application:
    name: myspringcloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


info:
  app.name: scauly-myspringcloud
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

zuul:
  prefix: /scauly
  ignored-services: "*"
  routes:
    mydept.serviceId: myspringcloud
    mydept.path: /mydept/**
